### ISSUE TITLE
HMServer.jar slf4j

### ISSUE THREAD

**Issue by quickmic** [eq-3/occu#51]
Seems there is an issue with slf4j.

root@homematic:~# /usr/bin/java -Dlog4j.configuration=file:///etc/config/log4j.xml -jar /mnt/transfer/HMServer2.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at de.eq3.ccu.server.HMServer.initialize(HMServer.java:104)
	at de.eq3.ccu.server.HMServer.<init>(HMServer.java:60)
	at de.eq3.ccu.server.HMServer.main(HMServer.java:89)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: java.lang.ClassNotFoundException: de.eq3.cbcs.util.logging.slf4j.Slf4jLoggerFactory
	at de.eq3.cbcs.util.EQ3LoggerFactory.getLogger(EQ3LoggerFactory.java:51)
	at de.eq3.cbcs.vertx.management.VertxManager.<clinit>(VertxManager.java:47)
	... 3 more
Caused by: java.lang.ClassNotFoundException: de.eq3.cbcs.util.logging.slf4j.Slf4jLoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.eq3.cbcs.util.EQ3LoggerFactory.getLogger(EQ3LoggerFactory.java:44)
	... 4 more

**Comment by jp112sdl** [comment]
At first I had the same error. 

After unpacking the ejdk-8u131-linux-arm-sflt.tar.gz I used the files from the folder "compact3" which does not include the logger class.

After using the contents of the "jre" folder the slf4j does not appear anymore.

**Comment by quickmic** [comment]
Well, I tried with ejdk-8u131-linux-i586.tar.gz, cause I'm running ccu on x86 but the error still appears.

**Comment by jp112sdl** [comment]
Ok, now it is clear. You want to start the HMServer.jar while i started the HMIPServer.jar.
My mistake. But the HMIPServer.jar starts correctly.

**Comment by quickmic** [comment]
Yes, confirmed. HMIPServer.jar is ok. 
Also the HMServer.jar from Mar 30, 2017 (2.27.8) runs well.

**Comment by quickmic** [comment]
Update:
I patched the current git version and works now.
I copied a couple of (logging) files/folders from the last functional version (2.27) to the new 2.29x.
If required, I could make a list...

**Comment by quickmic** [comment]
Issue is still present in the latest version.
Following is missing in the 2.29x HMServer.jar compared to 2.27x:
\de\eq3\cbcs\util\logging\
\org\apache\log4j\
\META-INF\maven\log4j\
\META-INF\maven\org.slf4j\slf4j-log4j12\
\META-INF\maven\de.eq3.cbcs.util\eq3-slf4j\
\META-INF\maven\de.eq3.cbcs.util\eq3-slf4j-core\
\org\slf4j\impl\

**Comment by eq-3-occu** [comment]
fixed with 71ed37eab3d7b140a93cf0e6f4af60e2bf573194
